/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_malacca_archives_BSDiff */

#ifndef _Included_com_malacca_archives_BSDiff
#define _Included_com_malacca_archives_BSDiff
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_malacca_archives_BSDiff
 * Method:    patch
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_malacca_archives_BSDiff_patch
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
